### ISSUE TITLE
TestFlight full?

### ISSUE THREAD

**Issue by habi** [wtimme/OSM-Surveyor#8]
The TestFlight Beta cannot be joined (see screenshot); is it full?

![image](https://user-images.githubusercontent.com/1651235/102321130-87fe8b80-3f7d-11eb-8415-7333c51faa68.jpeg)

**Comment by wtimme** [comment]
The actual reason why it is not possible at the moment to join the Beta is the fact that my Apple Developer Program membership has expired. Since I am currently not using an iOS device, I do not have any plans to renew it anytime soon.

If you had Xcode installed locally on your maschine, you should be able to deploy the app to the device with your own account. Let me know if the README needs to be updated with more detailled steps in this regards.

**Comment by habi** [comment]
Does that mean that OSM-Surveyor is technically dead?

**Comment by wtimme** [comment]
Thanks for your question! I would not necessarily say that it is dead. Rather, it is not under active development right now.

However, personally, instead of copying the logic from StreetComplete to Swift, I would rather invest my time in streetcomplete/StreetComplete#1892, which seems more sustainable and future-proof, since the Android app is under active development.
